# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oam-qgis-plugin.ui'
#
# Created: Tue Jun 23 11:53:38 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(668, 376)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(40, 25, 596, 331))
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 210, 91, 26))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 110, 46, 16))
        self.label.setStyleSheet(_fromUtf8("color: rgb(132, 132, 132);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(70, 105, 151, 26))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.verticalScrollBar = QtGui.QScrollBar(self.tab)
        self.verticalScrollBar.setGeometry(QtCore.QRect(545, 45, 20, 151))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName(_fromUtf8("verticalScrollBar"))
        self.comboBox_2 = QtGui.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(25, 70, 231, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.toolButton = QtGui.QToolButton(self.tab)
        self.toolButton.setGeometry(QtCore.QRect(225, 105, 31, 26))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(25, 30, 226, 26))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.pushButton_8 = QtGui.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(415, 210, 71, 27))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(500, 210, 66, 27))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.tab)
        self.pushButton_10.setGeometry(QtCore.QRect(110, 155, 71, 27))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(310, 45, 236, 151))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(340, 55, 59, 14))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(335, 80, 59, 14))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(315, 105, 59, 14))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(315, 130, 59, 14))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(320, 155, 59, 14))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(320, 180, 59, 14))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(315, 205, 59, 14))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(315, 230, 59, 14))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(380, 50, 191, 22))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 75, 191, 22))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(380, 100, 191, 22))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(380, 125, 191, 22))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(380, 150, 191, 22))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(380, 175, 191, 22))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(380, 200, 191, 22))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(380, 225, 191, 22))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 231, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(315, 255, 71, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(395, 255, 76, 27))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalScrollBar_2 = QtGui.QScrollBar(self.tab_2)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(240, 50, 20, 216))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName(_fromUtf8("verticalScrollBar_2"))
        self.listWidget_2 = QtGui.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(20, 50, 221, 216))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(478, 255, 91, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.checkBox = QtGui.QCheckBox(self.tab_3)
        self.checkBox.setGeometry(QtCore.QRect(305, 50, 251, 20))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_2.setGeometry(QtCore.QRect(305, 75, 226, 20))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_3.setGeometry(QtCore.QRect(305, 100, 231, 20))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_4.setGeometry(QtCore.QRect(305, 125, 226, 20))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(310, 200, 58, 14))
        self.label_22.setStyleSheet(_fromUtf8(""))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.comboBox = QtGui.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(385, 165, 191, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(310, 170, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(385, 195, 191, 26))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.verticalScrollBar_4 = QtGui.QScrollBar(self.tab_3)
        self.verticalScrollBar_4.setGeometry(QtCore.QRect(250, 55, 20, 211))
        self.verticalScrollBar_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_4.setObjectName(_fromUtf8("verticalScrollBar_4"))
        self.columnView_3 = QtGui.QColumnView(self.tab_3)
        self.columnView_3.setGeometry(QtCore.QRect(30, 55, 221, 211))
        self.columnView_3.setObjectName(_fromUtf8("columnView_3"))
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(35, 20, 161, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 255, 89, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(445, 255, 89, 27))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.pushButton_2.setText(_translate("Dialog", "Remove", None))
        self.label.setText(_translate("Dialog", "File:", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Layer 1", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Layer 2", None))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Layer 3", None))
        self.comboBox_2.setItemText(3, _translate("Dialog", "From file...", None))
        self.toolButton.setText(_translate("Dialog", "...", None))
        self.label_23.setText(_translate("Dialog", "Select and include imagery sources", None))
        self.pushButton_8.setText(_translate("Dialog", "Up", None))
        self.pushButton_9.setText(_translate("Dialog", "Down", None))
        self.pushButton_10.setText(_translate("Dialog", "Add", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Imagery", None))
        self.label_2.setText(_translate("Dialog", "Title:", None))
        self.label_3.setText(_translate("Dialog", "Tags:", None))
        self.label_4.setText(_translate("Dialog", "Provider:", None))
        self.label_5.setText(_translate("Dialog", "Platform:", None))
        self.label_6.setText(_translate("Dialog", "Sensor:", None))
        self.label_7.setText(_translate("Dialog", "License:", None))
        self.label_8.setText(_translate("Dialog", "Website:", None))
        self.label_9.setText(_translate("Dialog", "Contact:", None))
        self.label_13.setText(_translate("Dialog", "Select sources to edit metadata:", None))
        self.pushButton_3.setText(_translate("Dialog", "Save", None))
        self.pushButton_7.setText(_translate("Dialog", "Clean", None))
        self.pushButton.setText(_translate("Dialog", "As previous", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Metadata", None))
        self.checkBox.setText(_translate("Dialog", "Notify OAM of new resource", None))
        self.checkBox_2.setText(_translate("Dialog", "Trigger OAM tile service", None))
        self.checkBox_3.setText(_translate("Dialog", "Reproject to EPSG:3857", None))
        self.checkBox_4.setText(_translate("Dialog", "Convert format to GeoTIFF RGB", None))
        self.label_22.setText(_translate("Dialog", "Key:", None))
        self.comboBox.setItemText(0, _translate("Dialog", "OAM S3 bucket", None))
        self.comboBox.setItemText(1, _translate("Dialog", "Digital Globe", None))
        self.label_10.setText(_translate("Dialog", "Storage:", None))
        self.label_20.setText(_translate("Dialog", "Review full metadata file:", None))
        self.pushButton_4.setText(_translate("Dialog", "Upload", None))
        self.pushButton_5.setText(_translate("Dialog", "Cancel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Upload", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

