# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/img_uploader_wizard.ui'
#
# Created: Wed Aug 26 15:51:50 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName(_fromUtf8("Wizard"))
        Wizard.resize(747, 472)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.select_source_label = QtGui.QLabel(self.wizardPage1)
        self.select_source_label.setMaximumSize(QtCore.QSize(191, 16777215))
        self.select_source_label.setObjectName(_fromUtf8("select_source_label"))
        self.horizontalLayout.addWidget(self.select_source_label)
        self.layers_tool_button = QtGui.QToolButton(self.wizardPage1)
        self.layers_tool_button.setObjectName(_fromUtf8("layers_tool_button"))
        self.horizontalLayout.addWidget(self.layers_tool_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layers_list_widget = QtGui.QListWidget(self.wizardPage1)
        self.layers_list_widget.setLineWidth(2)
        self.layers_list_widget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.layers_list_widget.setObjectName(_fromUtf8("layers_list_widget"))
        self.verticalLayout.addWidget(self.layers_list_widget)
        self.file_label = QtGui.QLabel(self.wizardPage1)
        self.file_label.setStyleSheet(_fromUtf8(""))
        self.file_label.setObjectName(_fromUtf8("file_label"))
        self.verticalLayout.addWidget(self.file_label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.source_file_edit = QtGui.QLineEdit(self.wizardPage1)
        self.source_file_edit.setObjectName(_fromUtf8("source_file_edit"))
        self.horizontalLayout_2.addWidget(self.source_file_edit)
        self.file_tool_button = QtGui.QToolButton(self.wizardPage1)
        self.file_tool_button.setObjectName(_fromUtf8("file_tool_button"))
        self.horizontalLayout_2.addWidget(self.file_tool_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem = QtGui.QSpacerItem(20, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.add_source_button = QtGui.QPushButton(self.wizardPage1)
        self.add_source_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.add_source_button.setObjectName(_fromUtf8("add_source_button"))
        self.verticalLayout_3.addWidget(self.add_source_button)
        self.remove_source_button = QtGui.QPushButton(self.wizardPage1)
        self.remove_source_button.setObjectName(_fromUtf8("remove_source_button"))
        self.verticalLayout_3.addWidget(self.remove_source_button)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.reorganize_label = QtGui.QLabel(self.wizardPage1)
        self.reorganize_label.setObjectName(_fromUtf8("reorganize_label"))
        self.verticalLayout_2.addWidget(self.reorganize_label)
        self.sources_list_widget = QtGui.QListWidget(self.wizardPage1)
        self.sources_list_widget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.sources_list_widget.setObjectName(_fromUtf8("sources_list_widget"))
        self.verticalLayout_2.addWidget(self.sources_list_widget)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        spacerItem2 = QtGui.QSpacerItem(20, 83, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.up_source_button = QtGui.QPushButton(self.wizardPage1)
        self.up_source_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.up_source_button.setObjectName(_fromUtf8("up_source_button"))
        self.verticalLayout_9.addWidget(self.up_source_button)
        self.down_source_button = QtGui.QPushButton(self.wizardPage1)
        self.down_source_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.down_source_button.setObjectName(_fromUtf8("down_source_button"))
        self.verticalLayout_9.addWidget(self.down_source_button)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        spacerItem3 = QtGui.QSpacerItem(20, 103, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem5 = QtGui.QSpacerItem(20, 43, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.default_button = QtGui.QPushButton(self.wizardPage2)
        self.default_button.setObjectName(_fromUtf8("default_button"))
        self.verticalLayout_4.addWidget(self.default_button)
        self.clean_button = QtGui.QPushButton(self.wizardPage2)
        self.clean_button.setObjectName(_fromUtf8("clean_button"))
        self.verticalLayout_4.addWidget(self.clean_button)
        self.save_button = QtGui.QPushButton(self.wizardPage2)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.verticalLayout_4.addWidget(self.save_button)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem6 = QtGui.QSpacerItem(20, 108, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.select_source_metadata_label = QtGui.QLabel(self.wizardPage2)
        self.select_source_metadata_label.setObjectName(_fromUtf8("select_source_metadata_label"))
        self.verticalLayout_5.addWidget(self.select_source_metadata_label)
        self.added_sources_list_widget = QtGui.QListWidget(self.wizardPage2)
        self.added_sources_list_widget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.added_sources_list_widget.setObjectName(_fromUtf8("added_sources_list_widget"))
        self.verticalLayout_5.addWidget(self.added_sources_list_widget)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.formLayout_1 = QtGui.QFormLayout()
        self.formLayout_1.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_1.setVerticalSpacing(2)
        self.formLayout_1.setObjectName(_fromUtf8("formLayout_1"))
        self.title_label = QtGui.QLabel(self.wizardPage2)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.formLayout_1.setWidget(0, QtGui.QFormLayout.LabelRole, self.title_label)
        self.title_edit = QtGui.QLineEdit(self.wizardPage2)
        self.title_edit.setObjectName(_fromUtf8("title_edit"))
        self.formLayout_1.setWidget(0, QtGui.QFormLayout.FieldRole, self.title_edit)
        self.platform_label = QtGui.QLabel(self.wizardPage2)
        self.platform_label.setObjectName(_fromUtf8("platform_label"))
        self.formLayout_1.setWidget(1, QtGui.QFormLayout.LabelRole, self.platform_label)
        self.platform_combo_box = QtGui.QComboBox(self.wizardPage2)
        self.platform_combo_box.setObjectName(_fromUtf8("platform_combo_box"))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.formLayout_1.setWidget(1, QtGui.QFormLayout.FieldRole, self.platform_combo_box)
        self.sensor_label = QtGui.QLabel(self.wizardPage2)
        self.sensor_label.setObjectName(_fromUtf8("sensor_label"))
        self.formLayout_1.setWidget(2, QtGui.QFormLayout.LabelRole, self.sensor_label)
        self.sensor_edit = QtGui.QLineEdit(self.wizardPage2)
        self.sensor_edit.setObjectName(_fromUtf8("sensor_edit"))
        self.formLayout_1.setWidget(2, QtGui.QFormLayout.FieldRole, self.sensor_edit)
        self.sense_start_label = QtGui.QLabel(self.wizardPage2)
        self.sense_start_label.setObjectName(_fromUtf8("sense_start_label"))
        self.formLayout_1.setWidget(3, QtGui.QFormLayout.LabelRole, self.sense_start_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sense_start_edit = QtGui.QDateTimeEdit(self.wizardPage2)
        self.sense_start_edit.setObjectName(_fromUtf8("sense_start_edit"))
        self.horizontalLayout_3.addWidget(self.sense_start_edit)
        self.formLayout_1.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.sense_end_label = QtGui.QLabel(self.wizardPage2)
        self.sense_end_label.setObjectName(_fromUtf8("sense_end_label"))
        self.formLayout_1.setWidget(5, QtGui.QFormLayout.LabelRole, self.sense_end_label)
        self.sense_end_edit = QtGui.QDateTimeEdit(self.wizardPage2)
        self.sense_end_edit.setObjectName(_fromUtf8("sense_end_edit"))
        self.formLayout_1.setWidget(5, QtGui.QFormLayout.FieldRole, self.sense_end_edit)
        self.tags_label = QtGui.QLabel(self.wizardPage2)
        self.tags_label.setObjectName(_fromUtf8("tags_label"))
        self.formLayout_1.setWidget(6, QtGui.QFormLayout.LabelRole, self.tags_label)
        self.tags_edit = QtGui.QLineEdit(self.wizardPage2)
        self.tags_edit.setObjectName(_fromUtf8("tags_edit"))
        self.formLayout_1.setWidget(6, QtGui.QFormLayout.FieldRole, self.tags_edit)
        self.provider_label = QtGui.QLabel(self.wizardPage2)
        self.provider_label.setObjectName(_fromUtf8("provider_label"))
        self.formLayout_1.setWidget(7, QtGui.QFormLayout.LabelRole, self.provider_label)
        self.provider_edit = QtGui.QLineEdit(self.wizardPage2)
        self.provider_edit.setObjectName(_fromUtf8("provider_edit"))
        self.formLayout_1.setWidget(7, QtGui.QFormLayout.FieldRole, self.provider_edit)
        self.contact_label = QtGui.QLabel(self.wizardPage2)
        self.contact_label.setObjectName(_fromUtf8("contact_label"))
        self.formLayout_1.setWidget(8, QtGui.QFormLayout.LabelRole, self.contact_label)
        self.contact_edit = QtGui.QLineEdit(self.wizardPage2)
        self.contact_edit.setCursorPosition(0)
        self.contact_edit.setObjectName(_fromUtf8("contact_edit"))
        self.formLayout_1.setWidget(8, QtGui.QFormLayout.FieldRole, self.contact_edit)
        self.website_label = QtGui.QLabel(self.wizardPage2)
        self.website_label.setObjectName(_fromUtf8("website_label"))
        self.formLayout_1.setWidget(9, QtGui.QFormLayout.LabelRole, self.website_label)
        self.website_edit = QtGui.QLineEdit(self.wizardPage2)
        self.website_edit.setObjectName(_fromUtf8("website_edit"))
        self.formLayout_1.setWidget(9, QtGui.QFormLayout.FieldRole, self.website_edit)
        self.license_check_box = QtGui.QCheckBox(self.wizardPage2)
        self.license_check_box.setObjectName(_fromUtf8("license_check_box"))
        self.formLayout_1.setWidget(10, QtGui.QFormLayout.SpanningRole, self.license_check_box)
        self.gridLayout.addLayout(self.formLayout_1, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 1, 0, 1, 1)
        Wizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wizardPage3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.review_metadata_label = QtGui.QLabel(self.wizardPage3)
        self.review_metadata_label.setObjectName(_fromUtf8("review_metadata_label"))
        self.verticalLayout_10.addWidget(self.review_metadata_label)
        self.metadata_review_browser = QtGui.QTextBrowser(self.wizardPage3)
        self.metadata_review_browser.setObjectName(_fromUtf8("metadata_review_browser"))
        self.verticalLayout_10.addWidget(self.metadata_review_browser)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setVerticalSpacing(2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.storage_label = QtGui.QLabel(self.wizardPage3)
        self.storage_label.setObjectName(_fromUtf8("storage_label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.storage_label)
        self.storage_combo_box = QtGui.QComboBox(self.wizardPage3)
        self.storage_combo_box.setEditable(False)
        self.storage_combo_box.setObjectName(_fromUtf8("storage_combo_box"))
        self.storage_combo_box.addItem(_fromUtf8(""))
        self.storage_combo_box.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.storage_combo_box)
        self.specify_label = QtGui.QLabel(self.wizardPage3)
        self.specify_label.setEnabled(False)
        self.specify_label.setObjectName(_fromUtf8("specify_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.specify_label)
        self.specify_edit = QtGui.QLineEdit(self.wizardPage3)
        self.specify_edit.setEnabled(False)
        self.specify_edit.setText(_fromUtf8(""))
        self.specify_edit.setObjectName(_fromUtf8("specify_edit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.specify_edit)
        self.key_id_label = QtGui.QLabel(self.wizardPage3)
        self.key_id_label.setStyleSheet(_fromUtf8(""))
        self.key_id_label.setObjectName(_fromUtf8("key_id_label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.key_id_label)
        self.key_id_edit = QtGui.QLineEdit(self.wizardPage3)
        self.key_id_edit.setObjectName(_fromUtf8("key_id_edit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.key_id_edit)
        self.secret_key_label = QtGui.QLabel(self.wizardPage3)
        self.secret_key_label.setStyleSheet(_fromUtf8(""))
        self.secret_key_label.setObjectName(_fromUtf8("secret_key_label"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.secret_key_label)
        self.secret_key_edit = QtGui.QLineEdit(self.wizardPage3)
        self.secret_key_edit.setObjectName(_fromUtf8("secret_key_edit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.secret_key_edit)
        self.verticalLayout_11.addLayout(self.formLayout_2)
        self.trigger_tiling_check = QtGui.QCheckBox(self.wizardPage3)
        self.trigger_tiling_check.setObjectName(_fromUtf8("trigger_tiling_check"))
        self.verticalLayout_11.addWidget(self.trigger_tiling_check)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 53, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem9, 1, 0, 1, 1)
        Wizard.addPage(self.wizardPage3)

        self.retranslateUi(Wizard)
        self.storage_combo_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(_translate("Wizard", "Wizard", None))
        self.wizardPage1.setTitle(_translate("Wizard", "Select and sort Imagery", None))
        self.wizardPage1.setSubTitle(_translate("Wizard", "Please choose imagery among the loaded layers in QGIS or select files from the file system", None))
        self.select_source_label.setText(_translate("Wizard", "Select layers", None))
        self.layers_tool_button.setToolTip(_translate("Wizard", "Reload layers", None))
        self.layers_tool_button.setText(_translate("Wizard", "...", None))
        self.layers_list_widget.setToolTip(_translate("Wizard", "Select layers to be uploaded", None))
        self.file_label.setText(_translate("Wizard", "   Select file", None))
        self.source_file_edit.setToolTip(_translate("Wizard", "Select file using tool button on the right ", None))
        self.file_tool_button.setText(_translate("Wizard", "...", None))
        self.add_source_button.setToolTip(_translate("Wizard", "Add selected imagery source", None))
        self.add_source_button.setText(_translate("Wizard", ">", None))
        self.remove_source_button.setToolTip(_translate("Wizard", "Remove selected imagery source", None))
        self.remove_source_button.setText(_translate("Wizard", "<", None))
        self.reorganize_label.setText(_translate("Wizard", "Sources in order of upload", None))
        self.sources_list_widget.setToolTip(_translate("Wizard", "Reorganize and change the upload order", None))
        self.up_source_button.setToolTip(_translate("Wizard", "Move selected source up", None))
        self.up_source_button.setText(_translate("Wizard", "Up", None))
        self.down_source_button.setToolTip(_translate("Wizard", "Move selected source down", None))
        self.down_source_button.setText(_translate("Wizard", "Down", None))
        self.wizardPage2.setTitle(_translate("Wizard", "Provide imagery metadata", None))
        self.wizardPage2.setSubTitle(_translate("Wizard", "First select which imagery you will input metadata, then fil lthe form and save. You need to provide metadata for all source imagery before attempting to upload.", None))
        self.default_button.setText(_translate("Wizard", "Default", None))
        self.clean_button.setText(_translate("Wizard", "Clean", None))
        self.save_button.setText(_translate("Wizard", "Save", None))
        self.select_source_metadata_label.setText(_translate("Wizard", "Sources to edit metadata", None))
        self.title_label.setText(_translate("Wizard", "Title:", None))
        self.title_edit.setToolTip(_translate("Wizard", "Human friendly title of the image", None))
        self.platform_label.setText(_translate("Wizard", "Platform:", None))
        self.platform_combo_box.setItemText(0, _translate("Wizard", "satellite", None))
        self.platform_combo_box.setItemText(1, _translate("Wizard", "aircraft", None))
        self.platform_combo_box.setItemText(2, _translate("Wizard", "UAV", None))
        self.platform_combo_box.setItemText(3, _translate("Wizard", "balloon", None))
        self.platform_combo_box.setItemText(4, _translate("Wizard", "kite", None))
        self.sensor_label.setText(_translate("Wizard", "Sensor:", None))
        self.sensor_edit.setToolTip(_translate("Wizard", "Image aquisition device (eg. camera, radar, etc)", None))
        self.sense_start_label.setText(_translate("Wizard", "Sense start", None))
        self.sense_end_label.setText(_translate("Wizard", "Sense end", None))
        self.tags_label.setText(_translate("Wizard", "Tags:", None))
        self.tags_edit.setToolTip(_translate("Wizard", "Free tags separated by comma", None))
        self.provider_label.setText(_translate("Wizard", "Provider:", None))
        self.provider_edit.setToolTip(_translate("Wizard", "Provider/owner of the OIN bucket", None))
        self.contact_label.setText(_translate("Wizard", "Contact:", None))
        self.contact_edit.setToolTip(_translate("Wizard", "Name and email address of the data provider", None))
        self.website_label.setText(_translate("Wizard", "Website:", None))
        self.website_edit.setToolTip(_translate("Wizard", "Website of the data provider", None))
        self.license_check_box.setText(_translate("Wizard", "In accordance with OAM free license terms", None))
        self.wizardPage3.setTitle(_translate("Wizard", "Review metadata and upload", None))
        self.wizardPage3.setSubTitle(_translate("Wizard", "If the metadata presented is correct, you can finish the wizard and proceed to upload. If you notice any mistake, please go back and correct it.", None))
        self.review_metadata_label.setText(_translate("Wizard", "Review sources metadata", None))
        self.metadata_review_browser.setToolTip(_translate("Wizard", "Review full metadata to be uploaded and go back to the Metadata tab in case changes need to be done", None))
        self.storage_label.setText(_translate("Wizard", "AWS Bucket", None))
        self.storage_combo_box.setItemText(0, _translate("Wizard", "oam-qgis-plugin-test", None))
        self.storage_combo_box.setItemText(1, _translate("Wizard", "other...", None))
        self.specify_label.setText(_translate("Wizard", "   Specify", None))
        self.specify_edit.setToolTip(_translate("Wizard", "Bucket name which is not listed above ", None))
        self.key_id_label.setText(_translate("Wizard", "Key-id", None))
        self.key_id_edit.setToolTip(_translate("Wizard", "AWS access key id", None))
        self.secret_key_label.setText(_translate("Wizard", "Secret key", None))
        self.secret_key_edit.setToolTip(_translate("Wizard", "AWS secret access key", None))
        self.trigger_tiling_check.setText(_translate("Wizard", "Trigger OAM tile service", None))

