# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/oam_client_dialog_base.ui'
#
# Created: Sun Aug 16 01:42:11 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OpenAerialMapDialogBase(object):
    def setupUi(self, OpenAerialMapDialogBase):
        OpenAerialMapDialogBase.setObjectName(_fromUtf8("OpenAerialMapDialogBase"))
        OpenAerialMapDialogBase.resize(740, 413)
        self.gridLayout = QtGui.QGridLayout(OpenAerialMapDialogBase)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tab_widget = QtGui.QTabWidget(OpenAerialMapDialogBase)
        self.tab_widget.setToolTip(_fromUtf8(""))
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.imagery_tab = QtGui.QWidget()
        self.imagery_tab.setObjectName(_fromUtf8("imagery_tab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.imagery_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 109, 61, 56))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.add_source_button = QtGui.QPushButton(self.verticalLayoutWidget)
        self.add_source_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.add_source_button.setObjectName(_fromUtf8("add_source_button"))
        self.verticalLayout_3.addWidget(self.add_source_button)
        self.remove_source_button = QtGui.QPushButton(self.verticalLayoutWidget)
        self.remove_source_button.setObjectName(_fromUtf8("remove_source_button"))
        self.verticalLayout_3.addWidget(self.remove_source_button)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.imagery_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(625, 104, 71, 61))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.up_source_button = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.up_source_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.up_source_button.setObjectName(_fromUtf8("up_source_button"))
        self.verticalLayout_9.addWidget(self.up_source_button)
        self.down_source_button = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.down_source_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.down_source_button.setObjectName(_fromUtf8("down_source_button"))
        self.verticalLayout_9.addWidget(self.down_source_button)
        self.layoutWidget = QtGui.QWidget(self.imagery_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 25, 246, 271))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.reorganize_label = QtGui.QLabel(self.layoutWidget)
        self.reorganize_label.setObjectName(_fromUtf8("reorganize_label"))
        self.verticalLayout_2.addWidget(self.reorganize_label)
        self.sources_list_widget = QtGui.QListWidget(self.layoutWidget)
        self.sources_list_widget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.sources_list_widget.setObjectName(_fromUtf8("sources_list_widget"))
        self.verticalLayout_2.addWidget(self.sources_list_widget)
        self.layoutWidget1 = QtGui.QWidget(self.imagery_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 25, 231, 271))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_1 = QtGui.QVBoxLayout()
        self.verticalLayout_1.setObjectName(_fromUtf8("verticalLayout_1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.select_source_label = QtGui.QLabel(self.layoutWidget1)
        self.select_source_label.setMaximumSize(QtCore.QSize(191, 16777215))
        self.select_source_label.setObjectName(_fromUtf8("select_source_label"))
        self.horizontalLayout_4.addWidget(self.select_source_label)
        self.layers_tool_button = QtGui.QToolButton(self.layoutWidget1)
        self.layers_tool_button.setObjectName(_fromUtf8("layers_tool_button"))
        self.horizontalLayout_4.addWidget(self.layers_tool_button)
        self.verticalLayout_1.addLayout(self.horizontalLayout_4)
        self.layers_list_widget = QtGui.QListWidget(self.layoutWidget1)
        self.layers_list_widget.setLineWidth(2)
        self.layers_list_widget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.layers_list_widget.setObjectName(_fromUtf8("layers_list_widget"))
        self.verticalLayout_1.addWidget(self.layers_list_widget)
        self.verticalLayout.addLayout(self.verticalLayout_1)
        self.file_label = QtGui.QLabel(self.layoutWidget1)
        self.file_label.setStyleSheet(_fromUtf8(""))
        self.file_label.setObjectName(_fromUtf8("file_label"))
        self.verticalLayout.addWidget(self.file_label)
        self.horizontalLayout_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_1.setObjectName(_fromUtf8("horizontalLayout_1"))
        self.source_file_edit = QtGui.QLineEdit(self.layoutWidget1)
        self.source_file_edit.setObjectName(_fromUtf8("source_file_edit"))
        self.horizontalLayout_1.addWidget(self.source_file_edit)
        self.file_tool_button = QtGui.QToolButton(self.layoutWidget1)
        self.file_tool_button.setObjectName(_fromUtf8("file_tool_button"))
        self.horizontalLayout_1.addWidget(self.file_tool_button)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.imagery_next_button = QtGui.QPushButton(self.imagery_tab)
        self.imagery_next_button.setGeometry(QtCore.QRect(630, 265, 66, 27))
        self.imagery_next_button.setObjectName(_fromUtf8("imagery_next_button"))
        self.tab_widget.addTab(self.imagery_tab, _fromUtf8(""))
        self.metadata_tab = QtGui.QWidget()
        self.metadata_tab.setObjectName(_fromUtf8("metadata_tab"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.metadata_tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(275, 30, 321, 290))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_1 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_1.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_1.setMargin(0)
        self.formLayout_1.setVerticalSpacing(2)
        self.formLayout_1.setObjectName(_fromUtf8("formLayout_1"))
        self.title_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.formLayout_1.setWidget(0, QtGui.QFormLayout.LabelRole, self.title_label)
        self.title_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.title_edit.setObjectName(_fromUtf8("title_edit"))
        self.formLayout_1.setWidget(0, QtGui.QFormLayout.FieldRole, self.title_edit)
        self.platform_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.platform_label.setObjectName(_fromUtf8("platform_label"))
        self.formLayout_1.setWidget(1, QtGui.QFormLayout.LabelRole, self.platform_label)
        self.platform_combo_box = QtGui.QComboBox(self.formLayoutWidget_2)
        self.platform_combo_box.setObjectName(_fromUtf8("platform_combo_box"))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.formLayout_1.setWidget(1, QtGui.QFormLayout.FieldRole, self.platform_combo_box)
        self.sensor_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.sensor_label.setObjectName(_fromUtf8("sensor_label"))
        self.formLayout_1.setWidget(2, QtGui.QFormLayout.LabelRole, self.sensor_label)
        self.sensor_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.sensor_edit.setObjectName(_fromUtf8("sensor_edit"))
        self.formLayout_1.setWidget(2, QtGui.QFormLayout.FieldRole, self.sensor_edit)
        self.sense_start_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.sense_start_label.setObjectName(_fromUtf8("sense_start_label"))
        self.formLayout_1.setWidget(3, QtGui.QFormLayout.LabelRole, self.sense_start_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sense_start_edit = QtGui.QDateTimeEdit(self.formLayoutWidget_2)
        self.sense_start_edit.setObjectName(_fromUtf8("sense_start_edit"))
        self.horizontalLayout_3.addWidget(self.sense_start_edit)
        self.formLayout_1.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.sense_end_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.sense_end_label.setObjectName(_fromUtf8("sense_end_label"))
        self.formLayout_1.setWidget(5, QtGui.QFormLayout.LabelRole, self.sense_end_label)
        self.sense_end_edit = QtGui.QDateTimeEdit(self.formLayoutWidget_2)
        self.sense_end_edit.setObjectName(_fromUtf8("sense_end_edit"))
        self.formLayout_1.setWidget(5, QtGui.QFormLayout.FieldRole, self.sense_end_edit)
        self.tags_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.tags_label.setObjectName(_fromUtf8("tags_label"))
        self.formLayout_1.setWidget(6, QtGui.QFormLayout.LabelRole, self.tags_label)
        self.tags_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.tags_edit.setObjectName(_fromUtf8("tags_edit"))
        self.formLayout_1.setWidget(6, QtGui.QFormLayout.FieldRole, self.tags_edit)
        self.provider_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.provider_label.setObjectName(_fromUtf8("provider_label"))
        self.formLayout_1.setWidget(7, QtGui.QFormLayout.LabelRole, self.provider_label)
        self.provider_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.provider_edit.setObjectName(_fromUtf8("provider_edit"))
        self.formLayout_1.setWidget(7, QtGui.QFormLayout.FieldRole, self.provider_edit)
        self.contact_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.contact_label.setObjectName(_fromUtf8("contact_label"))
        self.formLayout_1.setWidget(8, QtGui.QFormLayout.LabelRole, self.contact_label)
        self.contact_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.contact_edit.setCursorPosition(0)
        self.contact_edit.setObjectName(_fromUtf8("contact_edit"))
        self.formLayout_1.setWidget(8, QtGui.QFormLayout.FieldRole, self.contact_edit)
        self.website_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.website_label.setObjectName(_fromUtf8("website_label"))
        self.formLayout_1.setWidget(9, QtGui.QFormLayout.LabelRole, self.website_label)
        self.website_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.website_edit.setObjectName(_fromUtf8("website_edit"))
        self.formLayout_1.setWidget(9, QtGui.QFormLayout.FieldRole, self.website_edit)
        self.license_check_box = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.license_check_box.setObjectName(_fromUtf8("license_check_box"))
        self.formLayout_1.setWidget(10, QtGui.QFormLayout.SpanningRole, self.license_check_box)
        self.layoutWidget2 = QtGui.QWidget(self.metadata_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(615, 90, 87, 95))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.default_button = QtGui.QPushButton(self.layoutWidget2)
        self.default_button.setObjectName(_fromUtf8("default_button"))
        self.verticalLayout_4.addWidget(self.default_button)
        self.clean_button = QtGui.QPushButton(self.layoutWidget2)
        self.clean_button.setObjectName(_fromUtf8("clean_button"))
        self.verticalLayout_4.addWidget(self.clean_button)
        self.save_button = QtGui.QPushButton(self.layoutWidget2)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.verticalLayout_4.addWidget(self.save_button)
        self.layoutWidget3 = QtGui.QWidget(self.metadata_tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(25, 30, 226, 271))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.select_source_metadata_label = QtGui.QLabel(self.layoutWidget3)
        self.select_source_metadata_label.setObjectName(_fromUtf8("select_source_metadata_label"))
        self.verticalLayout_5.addWidget(self.select_source_metadata_label)
        self.added_sources_list_widget = QtGui.QListWidget(self.layoutWidget3)
        self.added_sources_list_widget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.added_sources_list_widget.setObjectName(_fromUtf8("added_sources_list_widget"))
        self.verticalLayout_5.addWidget(self.added_sources_list_widget)
        self.widget = QtGui.QWidget(self.metadata_tab)
        self.widget.setGeometry(QtCore.QRect(615, 245, 87, 62))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.metadata_previous_button = QtGui.QPushButton(self.widget)
        self.metadata_previous_button.setObjectName(_fromUtf8("metadata_previous_button"))
        self.verticalLayout_10.addWidget(self.metadata_previous_button)
        self.metadata_next_button = QtGui.QPushButton(self.widget)
        self.metadata_next_button.setObjectName(_fromUtf8("metadata_next_button"))
        self.verticalLayout_10.addWidget(self.metadata_next_button)
        self.tab_widget.addTab(self.metadata_tab, _fromUtf8(""))
        self.upload_tab = QtGui.QWidget()
        self.upload_tab.setObjectName(_fromUtf8("upload_tab"))
        self.layoutWidget4 = QtGui.QWidget(self.upload_tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(25, 30, 258, 266))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.review_metadata_label = QtGui.QLabel(self.layoutWidget4)
        self.review_metadata_label.setObjectName(_fromUtf8("review_metadata_label"))
        self.verticalLayout_8.addWidget(self.review_metadata_label)
        self.metadata_review_browser = QtGui.QTextBrowser(self.layoutWidget4)
        self.metadata_review_browser.setObjectName(_fromUtf8("metadata_review_browser"))
        self.verticalLayout_8.addWidget(self.metadata_review_browser)
        self.layoutWidget5 = QtGui.QWidget(self.upload_tab)
        self.layoutWidget5.setGeometry(QtCore.QRect(315, 175, 266, 109))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget5)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setVerticalSpacing(2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.storage_label = QtGui.QLabel(self.layoutWidget5)
        self.storage_label.setObjectName(_fromUtf8("storage_label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.storage_label)
        self.storage_combo_box = QtGui.QComboBox(self.layoutWidget5)
        self.storage_combo_box.setEditable(False)
        self.storage_combo_box.setObjectName(_fromUtf8("storage_combo_box"))
        self.storage_combo_box.addItem(_fromUtf8(""))
        self.storage_combo_box.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.storage_combo_box)
        self.key_id_label = QtGui.QLabel(self.layoutWidget5)
        self.key_id_label.setStyleSheet(_fromUtf8(""))
        self.key_id_label.setObjectName(_fromUtf8("key_id_label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.key_id_label)
        self.key_id_edit = QtGui.QLineEdit(self.layoutWidget5)
        self.key_id_edit.setObjectName(_fromUtf8("key_id_edit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.key_id_edit)
        self.secret_key_label = QtGui.QLabel(self.layoutWidget5)
        self.secret_key_label.setStyleSheet(_fromUtf8(""))
        self.secret_key_label.setObjectName(_fromUtf8("secret_key_label"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.secret_key_label)
        self.secret_key_edit = QtGui.QLineEdit(self.layoutWidget5)
        self.secret_key_edit.setObjectName(_fromUtf8("secret_key_edit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.secret_key_edit)
        self.specify_label = QtGui.QLabel(self.layoutWidget5)
        self.specify_label.setEnabled(False)
        self.specify_label.setObjectName(_fromUtf8("specify_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.specify_label)
        self.specify_edit = QtGui.QLineEdit(self.layoutWidget5)
        self.specify_edit.setEnabled(False)
        self.specify_edit.setText(_fromUtf8(""))
        self.specify_edit.setObjectName(_fromUtf8("specify_edit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.specify_edit)
        self.layoutWidget6 = QtGui.QWidget(self.upload_tab)
        self.layoutWidget6.setGeometry(QtCore.QRect(315, 55, 261, 100))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.notify_oam_check = QtGui.QCheckBox(self.layoutWidget6)
        self.notify_oam_check.setObjectName(_fromUtf8("notify_oam_check"))
        self.verticalLayout_6.addWidget(self.notify_oam_check)
        self.trigger_tiling_check = QtGui.QCheckBox(self.layoutWidget6)
        self.trigger_tiling_check.setObjectName(_fromUtf8("trigger_tiling_check"))
        self.verticalLayout_6.addWidget(self.trigger_tiling_check)
        self.reproject_check = QtGui.QCheckBox(self.layoutWidget6)
        self.reproject_check.setObjectName(_fromUtf8("reproject_check"))
        self.verticalLayout_6.addWidget(self.reproject_check)
        self.convert_geotiff_rgb_check = QtGui.QCheckBox(self.layoutWidget6)
        self.convert_geotiff_rgb_check.setObjectName(_fromUtf8("convert_geotiff_rgb_check"))
        self.verticalLayout_6.addWidget(self.convert_geotiff_rgb_check)
        self.layoutWidget7 = QtGui.QWidget(self.upload_tab)
        self.layoutWidget7.setGeometry(QtCore.QRect(605, 70, 91, 186))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.quit_button = QtGui.QPushButton(self.layoutWidget7)
        self.quit_button.setObjectName(_fromUtf8("quit_button"))
        self.verticalLayout_7.addWidget(self.quit_button)
        self.upload_previous_button = QtGui.QPushButton(self.layoutWidget7)
        self.upload_previous_button.setObjectName(_fromUtf8("upload_previous_button"))
        self.verticalLayout_7.addWidget(self.upload_previous_button)
        self.upload_button = QtGui.QPushButton(self.layoutWidget7)
        self.upload_button.setObjectName(_fromUtf8("upload_button"))
        self.verticalLayout_7.addWidget(self.upload_button)
        self.tab_widget.addTab(self.upload_tab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tab_widget, 0, 0, 1, 1)

        self.retranslateUi(OpenAerialMapDialogBase)
        self.tab_widget.setCurrentIndex(0)
        self.storage_combo_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OpenAerialMapDialogBase)

    def retranslateUi(self, OpenAerialMapDialogBase):
        OpenAerialMapDialogBase.setWindowTitle(_translate("OpenAerialMapDialogBase", "Open Aerial Map (OAM)", None))
        self.add_source_button.setToolTip(_translate("OpenAerialMapDialogBase", "Add selected imagery source", None))
        self.add_source_button.setText(_translate("OpenAerialMapDialogBase", ">", None))
        self.remove_source_button.setToolTip(_translate("OpenAerialMapDialogBase", "Remove selected imagery source", None))
        self.remove_source_button.setText(_translate("OpenAerialMapDialogBase", "<", None))
        self.up_source_button.setToolTip(_translate("OpenAerialMapDialogBase", "Move selected source up", None))
        self.up_source_button.setText(_translate("OpenAerialMapDialogBase", "Up", None))
        self.down_source_button.setToolTip(_translate("OpenAerialMapDialogBase", "Move selected source down", None))
        self.down_source_button.setText(_translate("OpenAerialMapDialogBase", "Down", None))
        self.reorganize_label.setText(_translate("OpenAerialMapDialogBase", "Sources in order of upload", None))
        self.sources_list_widget.setToolTip(_translate("OpenAerialMapDialogBase", "Reorganize and change the upload order", None))
        self.select_source_label.setText(_translate("OpenAerialMapDialogBase", "From layers", None))
        self.layers_tool_button.setToolTip(_translate("OpenAerialMapDialogBase", "Reload layers", None))
        self.layers_tool_button.setText(_translate("OpenAerialMapDialogBase", "...", None))
        self.layers_list_widget.setToolTip(_translate("OpenAerialMapDialogBase", "Select layers to be uploaded", None))
        self.file_label.setText(_translate("OpenAerialMapDialogBase", "From file", None))
        self.source_file_edit.setToolTip(_translate("OpenAerialMapDialogBase", "Select file using tool button on the right ", None))
        self.file_tool_button.setText(_translate("OpenAerialMapDialogBase", "...", None))
        self.imagery_next_button.setToolTip(_translate("OpenAerialMapDialogBase", "Go to the next tab", None))
        self.imagery_next_button.setText(_translate("OpenAerialMapDialogBase", "Next", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.imagery_tab), _translate("OpenAerialMapDialogBase", "Imagery", None))
        self.title_label.setText(_translate("OpenAerialMapDialogBase", "Title:", None))
        self.title_edit.setToolTip(_translate("OpenAerialMapDialogBase", "Human friendly title of the image", None))
        self.platform_label.setText(_translate("OpenAerialMapDialogBase", "Platform:", None))
        self.platform_combo_box.setItemText(0, _translate("OpenAerialMapDialogBase", "satellite", None))
        self.platform_combo_box.setItemText(1, _translate("OpenAerialMapDialogBase", "aircraft", None))
        self.platform_combo_box.setItemText(2, _translate("OpenAerialMapDialogBase", "UAV", None))
        self.platform_combo_box.setItemText(3, _translate("OpenAerialMapDialogBase", "balloon", None))
        self.platform_combo_box.setItemText(4, _translate("OpenAerialMapDialogBase", "kite", None))
        self.sensor_label.setText(_translate("OpenAerialMapDialogBase", "Sensor:", None))
        self.sensor_edit.setToolTip(_translate("OpenAerialMapDialogBase", "Image aquisition device (eg. camera, radar, etc)", None))
        self.sense_start_label.setText(_translate("OpenAerialMapDialogBase", "Sense start", None))
        self.sense_end_label.setText(_translate("OpenAerialMapDialogBase", "Sense end", None))
        self.tags_label.setText(_translate("OpenAerialMapDialogBase", "Tags:", None))
        self.tags_edit.setToolTip(_translate("OpenAerialMapDialogBase", "Free tags separated by comma", None))
        self.provider_label.setText(_translate("OpenAerialMapDialogBase", "Provider:", None))
        self.provider_edit.setToolTip(_translate("OpenAerialMapDialogBase", "Provider/owner of the OIN bucket", None))
        self.contact_label.setText(_translate("OpenAerialMapDialogBase", "Contact:", None))
        self.contact_edit.setToolTip(_translate("OpenAerialMapDialogBase", "Name and email address of the data provider", None))
        self.website_label.setText(_translate("OpenAerialMapDialogBase", "Website:", None))
        self.website_edit.setToolTip(_translate("OpenAerialMapDialogBase", "Website of the data provider", None))
        self.license_check_box.setText(_translate("OpenAerialMapDialogBase", "In accordance with OAM free license terms", None))
        self.default_button.setText(_translate("OpenAerialMapDialogBase", "Default", None))
        self.clean_button.setText(_translate("OpenAerialMapDialogBase", "Clean", None))
        self.save_button.setText(_translate("OpenAerialMapDialogBase", "Save", None))
        self.select_source_metadata_label.setText(_translate("OpenAerialMapDialogBase", "Sources to edit metadata", None))
        self.metadata_previous_button.setText(_translate("OpenAerialMapDialogBase", "Previous", None))
        self.metadata_next_button.setToolTip(_translate("OpenAerialMapDialogBase", "Go to the next tab", None))
        self.metadata_next_button.setText(_translate("OpenAerialMapDialogBase", "Next", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.metadata_tab), _translate("OpenAerialMapDialogBase", "Metadata", None))
        self.review_metadata_label.setText(_translate("OpenAerialMapDialogBase", "Review sources metadata", None))
        self.metadata_review_browser.setToolTip(_translate("OpenAerialMapDialogBase", "Review full metadata to be uploaded and go back to the Metadata tab in case changes need to be done", None))
        self.storage_label.setText(_translate("OpenAerialMapDialogBase", "AWS Bucket", None))
        self.storage_combo_box.setItemText(0, _translate("OpenAerialMapDialogBase", "oam-qgis-plugin-test", None))
        self.storage_combo_box.setItemText(1, _translate("OpenAerialMapDialogBase", "other...", None))
        self.key_id_label.setText(_translate("OpenAerialMapDialogBase", "Key-id", None))
        self.key_id_edit.setToolTip(_translate("OpenAerialMapDialogBase", "AWS access key id", None))
        self.secret_key_label.setText(_translate("OpenAerialMapDialogBase", "Secret key", None))
        self.secret_key_edit.setToolTip(_translate("OpenAerialMapDialogBase", "AWS secret access key", None))
        self.specify_label.setText(_translate("OpenAerialMapDialogBase", "   Specify", None))
        self.specify_edit.setToolTip(_translate("OpenAerialMapDialogBase", "Bucket name which is not listed above ", None))
        self.notify_oam_check.setText(_translate("OpenAerialMapDialogBase", "Notify OAM of new resource", None))
        self.trigger_tiling_check.setText(_translate("OpenAerialMapDialogBase", "Trigger OAM tile service", None))
        self.reproject_check.setText(_translate("OpenAerialMapDialogBase", "Reproject to EPSG:3857", None))
        self.convert_geotiff_rgb_check.setText(_translate("OpenAerialMapDialogBase", "Convert format to GeoTIFF RGB", None))
        self.quit_button.setToolTip(_translate("OpenAerialMapDialogBase", "Quit plugin", None))
        self.quit_button.setText(_translate("OpenAerialMapDialogBase", "Quit", None))
        self.upload_previous_button.setText(_translate("OpenAerialMapDialogBase", "Previous", None))
        self.upload_button.setToolTip(_translate("OpenAerialMapDialogBase", "Upload imagery and metadata", None))
        self.upload_button.setText(_translate("OpenAerialMapDialogBase", "Upload", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.upload_tab), _translate("OpenAerialMapDialogBase", "Upload", None))

