# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/setting_dialog.ui'
#
# Created: Tue Sep  8 13:29:48 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(391, 596)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 565, 176, 27))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 5, 366, 291))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 25, 341, 256))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_1 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_1.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_1.setMargin(0)
        self.formLayout_1.setVerticalSpacing(2)
        self.formLayout_1.setObjectName(_fromUtf8("formLayout_1"))
        self.title_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.formLayout_1.setWidget(0, QtGui.QFormLayout.LabelRole, self.title_label)
        self.title_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.title_edit.setObjectName(_fromUtf8("title_edit"))
        self.formLayout_1.setWidget(0, QtGui.QFormLayout.FieldRole, self.title_edit)
        self.platform_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.platform_label.setObjectName(_fromUtf8("platform_label"))
        self.formLayout_1.setWidget(1, QtGui.QFormLayout.LabelRole, self.platform_label)
        self.platform_combo_box = QtGui.QComboBox(self.formLayoutWidget_2)
        self.platform_combo_box.setObjectName(_fromUtf8("platform_combo_box"))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.platform_combo_box.addItem(_fromUtf8(""))
        self.formLayout_1.setWidget(1, QtGui.QFormLayout.FieldRole, self.platform_combo_box)
        self.sensor_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.sensor_label.setObjectName(_fromUtf8("sensor_label"))
        self.formLayout_1.setWidget(2, QtGui.QFormLayout.LabelRole, self.sensor_label)
        self.sensor_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.sensor_edit.setObjectName(_fromUtf8("sensor_edit"))
        self.formLayout_1.setWidget(2, QtGui.QFormLayout.FieldRole, self.sensor_edit)
        self.sense_start_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.sense_start_label.setObjectName(_fromUtf8("sense_start_label"))
        self.formLayout_1.setWidget(3, QtGui.QFormLayout.LabelRole, self.sense_start_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sense_start_edit = QtGui.QDateTimeEdit(self.formLayoutWidget_2)
        self.sense_start_edit.setObjectName(_fromUtf8("sense_start_edit"))
        self.horizontalLayout_3.addWidget(self.sense_start_edit)
        self.formLayout_1.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.sense_end_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.sense_end_label.setObjectName(_fromUtf8("sense_end_label"))
        self.formLayout_1.setWidget(5, QtGui.QFormLayout.LabelRole, self.sense_end_label)
        self.sense_end_edit = QtGui.QDateTimeEdit(self.formLayoutWidget_2)
        self.sense_end_edit.setObjectName(_fromUtf8("sense_end_edit"))
        self.formLayout_1.setWidget(5, QtGui.QFormLayout.FieldRole, self.sense_end_edit)
        self.tags_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.tags_label.setObjectName(_fromUtf8("tags_label"))
        self.formLayout_1.setWidget(6, QtGui.QFormLayout.LabelRole, self.tags_label)
        self.tags_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.tags_edit.setObjectName(_fromUtf8("tags_edit"))
        self.formLayout_1.setWidget(6, QtGui.QFormLayout.FieldRole, self.tags_edit)
        self.provider_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.provider_label.setObjectName(_fromUtf8("provider_label"))
        self.formLayout_1.setWidget(7, QtGui.QFormLayout.LabelRole, self.provider_label)
        self.provider_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.provider_edit.setObjectName(_fromUtf8("provider_edit"))
        self.formLayout_1.setWidget(7, QtGui.QFormLayout.FieldRole, self.provider_edit)
        self.contact_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.contact_label.setObjectName(_fromUtf8("contact_label"))
        self.formLayout_1.setWidget(8, QtGui.QFormLayout.LabelRole, self.contact_label)
        self.contact_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.contact_edit.setCursorPosition(0)
        self.contact_edit.setObjectName(_fromUtf8("contact_edit"))
        self.formLayout_1.setWidget(8, QtGui.QFormLayout.FieldRole, self.contact_edit)
        self.website_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.website_label.setObjectName(_fromUtf8("website_label"))
        self.formLayout_1.setWidget(9, QtGui.QFormLayout.LabelRole, self.website_label)
        self.website_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.website_edit.setObjectName(_fromUtf8("website_edit"))
        self.formLayout_1.setWidget(9, QtGui.QFormLayout.FieldRole, self.website_edit)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 295, 351, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 341, 100))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.license_check_box = QtGui.QCheckBox(self.layoutWidget)
        self.license_check_box.setObjectName(_fromUtf8("license_check_box"))
        self.verticalLayout.addWidget(self.license_check_box)
        self.checkBox_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout.addWidget(self.checkBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 425, 356, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(15, 20, 341, 108))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget1)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setVerticalSpacing(2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.storage_label = QtGui.QLabel(self.layoutWidget1)
        self.storage_label.setObjectName(_fromUtf8("storage_label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.storage_label)
        self.storage_combo_box = QtGui.QComboBox(self.layoutWidget1)
        self.storage_combo_box.setEditable(False)
        self.storage_combo_box.setObjectName(_fromUtf8("storage_combo_box"))
        self.storage_combo_box.addItem(_fromUtf8(""))
        self.storage_combo_box.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.storage_combo_box)
        self.key_id_label = QtGui.QLabel(self.layoutWidget1)
        self.key_id_label.setStyleSheet(_fromUtf8(""))
        self.key_id_label.setObjectName(_fromUtf8("key_id_label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.key_id_label)
        self.key_id_edit = QtGui.QLineEdit(self.layoutWidget1)
        self.key_id_edit.setObjectName(_fromUtf8("key_id_edit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.key_id_edit)
        self.secret_key_label = QtGui.QLabel(self.layoutWidget1)
        self.secret_key_label.setStyleSheet(_fromUtf8(""))
        self.secret_key_label.setObjectName(_fromUtf8("secret_key_label"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.secret_key_label)
        self.secret_key_edit = QtGui.QLineEdit(self.layoutWidget1)
        self.secret_key_edit.setObjectName(_fromUtf8("secret_key_edit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.secret_key_edit)
        self.specify_label = QtGui.QLabel(self.layoutWidget1)
        self.specify_label.setEnabled(False)
        self.specify_label.setObjectName(_fromUtf8("specify_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.specify_label)
        self.specify_edit = QtGui.QLineEdit(self.layoutWidget1)
        self.specify_edit.setEnabled(False)
        self.specify_edit.setText(_fromUtf8(""))
        self.specify_edit.setObjectName(_fromUtf8("specify_edit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.specify_edit)

        self.retranslateUi(Dialog)
        self.storage_combo_box.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Edit Settings", None))
        self.groupBox.setTitle(_translate("Dialog", "Metadata", None))
        self.title_label.setText(_translate("Dialog", "Title:", None))
        self.title_edit.setToolTip(_translate("Dialog", "Human friendly title of the image", None))
        self.platform_label.setText(_translate("Dialog", "Platform:", None))
        self.platform_combo_box.setItemText(0, _translate("Dialog", "satellite", None))
        self.platform_combo_box.setItemText(1, _translate("Dialog", "aircraft", None))
        self.platform_combo_box.setItemText(2, _translate("Dialog", "UAV", None))
        self.platform_combo_box.setItemText(3, _translate("Dialog", "balloon", None))
        self.platform_combo_box.setItemText(4, _translate("Dialog", "kite", None))
        self.sensor_label.setText(_translate("Dialog", "Sensor:", None))
        self.sensor_edit.setToolTip(_translate("Dialog", "Image aquisition device (eg. camera, radar, etc)", None))
        self.sense_start_label.setText(_translate("Dialog", "Sense start", None))
        self.sense_end_label.setText(_translate("Dialog", "Sense end", None))
        self.tags_label.setText(_translate("Dialog", "Tags:", None))
        self.tags_edit.setToolTip(_translate("Dialog", "Free tags separated by comma", None))
        self.provider_label.setText(_translate("Dialog", "Provider:", None))
        self.provider_edit.setToolTip(_translate("Dialog", "Provider/owner of the OIN bucket", None))
        self.contact_label.setText(_translate("Dialog", "Contact:", None))
        self.contact_edit.setToolTip(_translate("Dialog", "Name and email address of the data provider", None))
        self.website_label.setText(_translate("Dialog", "Website:", None))
        self.website_edit.setToolTip(_translate("Dialog", "Website of the data provider", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Options", None))
        self.license_check_box.setText(_translate("Dialog", "In accordance with OAM free license terms", None))
        self.checkBox_3.setText(_translate("Dialog", "Reproject to EPSG:3857", None))
        self.checkBox.setText(_translate("Dialog", "Notify OAM of new upload", None))
        self.checkBox_2.setText(_translate("Dialog", "Trigger OAM tile service", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Storage", None))
        self.storage_label.setText(_translate("Dialog", "AWS Bucket", None))
        self.storage_combo_box.setItemText(0, _translate("Dialog", "oam-qgis-plugin-test", None))
        self.storage_combo_box.setItemText(1, _translate("Dialog", "other...", None))
        self.key_id_label.setText(_translate("Dialog", "Key-id", None))
        self.key_id_edit.setToolTip(_translate("Dialog", "AWS access key id", None))
        self.secret_key_label.setText(_translate("Dialog", "Secret key", None))
        self.secret_key_edit.setToolTip(_translate("Dialog", "AWS secret access key", None))
        self.specify_label.setText(_translate("Dialog", "   Specify", None))
        self.specify_edit.setToolTip(_translate("Dialog", "Bucket name which is not listed above ", None))

